os: osx
cache:
  directories:
    - $HOME/Library/Caches/Homebrew
before_install:
    - brew update
    - brew outdated nim || brew upgrade nim
install:
    - brew install nim
script:
    - nim c buildverify.nim
    - ./buildverify `which nim`
